resources:
- repo: self

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  displayName: 'Use specific node version'
  inputs:
    versionSpec: '8.12.0'

# all envitonment variables should be defined in vsts UI
- script: |
    npm install -g npm@6.8.0
    npm update
    bash shell/install.sh
    npm install -g typescript
    npm install -g @angular/cli
    npm install -g firebase-tools
    npm install -g @compodoc/ngd-cli
    npm run build-firebase
    npm run test-single-run-and-report-to-dist
    firebase deploy --token $FIREBASE_DEPLOY_TOKEN
  env:
    FIREBASE_DEPLOY_TOKEN: $(firebaseDeployToken)

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
